title: Huy Nguyen-Quang
description: Experimental, environmental, and agricultural economist
email: nguyenquanghuyib@gmail.com
markdown: kramdown

url: "https://nguyenquanghuyvn.github.io"
baseurl: ""
permalink: pretty
